### ISSUE TITLE
How is data preprocessing done？

### ISSUE THREAD

**Issue by ShellyWayZ** [vanlalruata/DDoS-attack-detection-and-mitigation-using-deep-neural-network-in-SDN-environment#1]
Hello Hnamte，I am a beginner and don't know how to preprocess data. Can you help me?

**Comment by vanlalruata** [comment]
> Hello Hnamte，I am a beginner and don't know how to preprocess data. Can you help me?

The code itself is available here...you can follow and feel free to improve or modify it for your use.
