### ISSUE TITLE
How the code runs and how to install the environment

### ISSUE THREAD

**Issue by lai3754** [vanlalruata/DDoS-attack-detection-and-mitigation-using-deep-neural-network-in-SDN-environment#2]
Hello Hnamte，I am a beginner .I would like to reproduce your code, but I don't know some of the specific environments and running procedures, can you help me?

**Comment by vanlalruata** [comment]
From what I understand to your question, you may need to go through "https://github.com/joshivaibhav/CustomSDNController"  and "https://brianlinkletter.com/2015/04/using-the-pox-sdn-controller/" for further practicality before you start this.

**Comment by lai3754** [comment]
When I run the code controller_dl.py, I need to import the module switch, and I'm not sure how I need to do that. The error is as follows:
  File "/home/mzhh/code/controller_dl.py", line 6, in <module>
    import switch
ModuleNotFoundError: No module named 'switch'

Thank you for answering my question!

**Comment by vanlalruata** [comment]
You can install the switch module.

pip install switch

**Comment by lai3754** [comment]
I'm running instance_algorithm2 and I noticed that some of the corresponding code is not complete, are you able to send the complete code, I'm a novice and I'm having a lot of problems reproducing this code. Or can I need your VM image? Thank you for answering my questions.

**Comment by vanlalruata** [comment]
Most important parts are included. As the code contains attacks simulation, therefore, I cannot paste the full code here.
